on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n FrontierSandbox -g FrontierSandboxbb28-rg --location "East US 2" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n FrontierSandbox --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n FrontierSandbox --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n FrontierSandbox --query passwords[0].value | xargs`"
    - uses: azure/docker-login@v1
      with:
        login-server: frontiersandbox.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/DevOps" -f  ".github/workflows/Docker.yaml" -t frontiersandbox.azurecr.io/nextgenaks:${{ github.sha }} --label dockerfile-path=.github/workflows/Docker.yaml
        docker push frontiersandbox.azurecr.io/nextgenaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_nextgenaks_kubeConfig }}

    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep nextgen-aks-devops | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace nextgen-aks-devops`
        fi
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: nextgen-aks-devops
        container-registry-url: frontiersandbox.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: nextgenaksdockerauth

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: nextgen-aks-devops
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          frontiersandbox.azurecr.io/nextgenaks:${{ github.sha }}
        imagepullsecrets: |
          nextgenaksdockerauth
